//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DuAnQLNCKH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Author
    {
        public int IdAu { get; set; }
        public string IdLe { get; set; }
        public int IdGr { get; set; }
    
        public virtual Grade Grade { get; set; }
        public virtual Information Information { get; set; }
    }
}
